import clsx from "clsx";
import Markdown from "./Markdown";
import Instruction from "./Instruction";
import ReportMessage, { ReportMessageProps } from "./ReportMessage";
import React from "react";
import { Components } from "react-markdown";
import { ExclamationCircleIcon } from "@heroicons/react/16/solid";

type ChatBubbleProps = {
  author: "user" | "system";
  contents:
    | { type: "typing" }
    | { type: "error" }
    | { type: "message"; message: string };
  report?: ReportMessageProps;
  components?: Partial<Components> | null;
  isFallbackModel?: boolean;
};

export default function ChatBubble({
  author,
  contents,
  report,
  components,
  isFallbackModel = false,
}: ChatBubbleProps) {
  const isSystem = author === "system";

  return (
    <div className={clsx("flex", isSystem ? "mr-6" : "ml-6")}>
      <div
        className={clsx(
          "inline-block p-3 sm:p-4 rounded-xl shadow relative break-words max-w-[90%]",
          isSystem && "bg-white rounded-bl-none",
          !isSystem &&
            "bg-gradient-to-b from-purple-500 to-purple-600 text-white rounded-br-none ml-auto",
        )}
      >
        <ChatBubbleContents
          contents={contents}
          isSystem={isSystem}
          components={components}
          isFallbackModel={isFallbackModel}
        />

        {report && <ReportMessage {...report} />}
      </div>
    </div>
  );
}

const ChatBubbleContents = React.memo(function ChatBubbleContents({
  contents,
  isSystem,
  components,
  isFallbackModel,
}: {
  contents: ChatBubbleProps["contents"];
  isSystem: boolean;
  components?: Partial<Components> | null;
  isFallbackModel?: boolean;
}) {
  if (contents.type === "typing") {
    return (
      <div className="flex gap-1" aria-label="Loading">
        <div className="w-2 h-2 rounded-full bg-slate-500 animate-pulse"></div>
        <div className="w-2 h-2 rounded-full bg-slate-500 animate-pulse animation-delay-1-3"></div>
        <div className="w-2 h-2 rounded-full bg-slate-500 animate-pulse animation-delay-2-3"></div>
      </div>
    );
  }

  if (contents.type === "error") {
    return (
      <Instruction variant="error">
        <strong>An error occurred.</strong> Please try again.
      </Instruction>
    );
  }

  return (
    <>
      {isFallbackModel && (
        <p className="flex items-center gap-2 text-slate-500 text-sm mb-2">
          <ExclamationCircleIcon className="w-5 h-5" />
          This answer was generated by a less performant AI due to provider rate
          limits.
        </p>
      )}
      <Markdown
        text={contents.message}
        className={isSystem ? undefined : "prose-userMessage"}
        components={components}
      />
    </>
  );
});
